/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurum.java;

import aurum.java.controller.TransactionController;
import aurum.java.model.Transaction;
import java.awt.Color;
import java.text.NumberFormat;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Ethan
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    private YearMonth mesSelecionado;
    private PanelTransactions transactionsPanel;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        // Define o mês atual como padrão ao iniciar
        this.mesSelecionado = YearMonth.now();

        // Adiciona a ABA de Categorias
        PanelCategorias categoriasPanel = new PanelCategorias();
        jTabbedPane.addTab("Gerenciar Categorias", categoriasPanel);
        
        transactionsPanel = new PanelTransactions(this);
        jTabbedPane.addTab("Gerenciar Transações", transactionsPanel);
        atualizarDashboard();
    }

    public void atualizarDashboard() {
        // Atualiza o JLabel com o mês selecionado
        Locale localeBrasil = new Locale("pt", "BR");
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("MMMM 'de' yyyy", localeBrasil);

        // Formata o texto e deixa a primeira letra maiúscula
        String mesFormatado = mesSelecionado.format(formatador);
        mesFormatado = mesFormatado.substring(0, 1).toUpperCase() + mesFormatado.substring(1);

        jLabelMesSelecionado.setText(mesFormatado);

        TransactionController transactionController = new TransactionController();
        double[] totais = transactionController.getDashboardTotals(this.mesSelecionado);

        double receitas = totais[0];
        double despesas = totais[1];
        double saldo = receitas - despesas;

        NumberFormat formatadorMoeda = NumberFormat.getCurrencyInstance(localeBrasil);
        jLabelReceitas.setText(formatadorMoeda.format(receitas));
        jLabelDespesas.setText(formatadorMoeda.format(despesas));
        jLabelSaldo.setText(formatadorMoeda.format(saldo));

        if (saldo < 0) {
            jLabelSaldo.setForeground(new Color(204, 0, 0));
        } else if (saldo > 0) {
            jLabelSaldo.setForeground(new Color(0, 204, 0));
        } else {
            jLabelSaldo.setForeground(Color.BLACK);
        }

        if (transactionsPanel != null) {
            transactionsPanel.atualizarTabela();
        }
    }

    public YearMonth getMesSelecionado() {
        return mesSelecionado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelDashboard1 = new javax.swing.JLabel();
        jPanelReceitas1 = new javax.swing.JPanel();
        jLabelReceitas = new javax.swing.JLabel();
        jPanelDespesas1 = new javax.swing.JPanel();
        jLabelDespesas = new javax.swing.JLabel();
        jPanelSaldo1 = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jLabelMesSelecionado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonAdicionarTransação = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConfiguracoes = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aurum");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelDashboard1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelDashboard1.setText("Dashboard");

        jPanelReceitas1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receitas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 204, 51))); // NOI18N

        jLabelReceitas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelReceitas.setForeground(new java.awt.Color(0, 204, 0));
        jLabelReceitas.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelReceitas1Layout = new javax.swing.GroupLayout(jPanelReceitas1);
        jPanelReceitas1.setLayout(jPanelReceitas1Layout);
        jPanelReceitas1Layout.setHorizontalGroup(
            jPanelReceitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceitas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelReceitas1Layout.setVerticalGroup(
            jPanelReceitas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceitas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReceitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDespesas1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Despesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabelDespesas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelDespesas.setForeground(new java.awt.Color(204, 0, 0));
        jLabelDespesas.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelDespesas1Layout = new javax.swing.GroupLayout(jPanelDespesas1);
        jPanelDespesas1.setLayout(jPanelDespesas1Layout);
        jPanelDespesas1Layout.setHorizontalGroup(
            jPanelDespesas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDespesas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDespesas1Layout.setVerticalGroup(
            jPanelDespesas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDespesas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDespesas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSaldo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelSaldo.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelSaldo1Layout = new javax.swing.GroupLayout(jPanelSaldo1);
        jPanelSaldo1.setLayout(jPanelSaldo1Layout);
        jPanelSaldo1Layout.setHorizontalGroup(
            jPanelSaldo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSaldo1Layout.setVerticalGroup(
            jPanelSaldo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldo1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelMesSelecionado.setText("Mês");

        jButtonAdicionarTransação.setText("Adicionar Transação");
        jButtonAdicionarTransação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarTransaçãoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdicionarTransação, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAdicionarTransação, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelReceitas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDespesas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSaldo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelMesSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDashboard1)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDashboard1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabelMesSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReceitas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDespesas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSaldo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Dashboard", jPanel2);

        jMenuConfiguracoes.setText("Definir Mês");
        jMenuConfiguracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConfiguracoesMouseClicked(evt);
            }
        });
        jMenuBar.add(jMenuConfiguracoes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdicionarTransaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarTransaçãoActionPerformed
        TransactionsFormView form = new TransactionsFormView(null, true, "income");
        form.setLocationRelativeTo(this);
        form.setVisible(true);

        if (form.isSalvo()) {
            Transaction novaTransacao = form.getTransaction();
            TransactionController controller = new TransactionController();
            controller.save(novaTransacao);
            atualizarDashboard();
            JOptionPane.showMessageDialog(
                this, 
                "Transação adicionada com sucesso!", 
                "✓ Sucesso", 
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonAdicionarTransaçãoActionPerformed

    private void jMenuConfiguracoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConfiguracoesMouseClicked
        // Spinner para o MÊS, com valor inicial do mês atual, mínimo 1, máximo 12
        JSpinner spinnerMes = new JSpinner(new SpinnerNumberModel(
                mesSelecionado.getMonthValue(), 1, 12, 1
        ));

        // Spinner para o ANO, com valor inicial do ano atual, minimo 1900, máximo 2500
        JSpinner spinnerAno = new JSpinner(new SpinnerNumberModel(
                mesSelecionado.getYear(), 1900, 2500, 1
        ));

        // Monta o painel que ficará dentro do diálogo
        JPanel painelSelecao = new JPanel();
        painelSelecao.add(new JLabel("Mês:"));
        painelSelecao.add(spinnerMes);
        painelSelecao.add(new JLabel("Ano:"));
        painelSelecao.add(spinnerAno);

        // Exibe o JOptionPane
        int resultado = JOptionPane.showConfirmDialog(
                this, // Janela pai (o próprio Dashboard)
                painelSelecao, // Componente customizado
                "Selecione o Mês e Ano", // Título da janela
                JOptionPane.OK_CANCEL_OPTION, // Botões OK e Cancelar
                JOptionPane.PLAIN_MESSAGE // Ícone
        );

        if (resultado == JOptionPane.OK_OPTION) {
            int ano = (int) spinnerAno.getValue();
            int mes = (int) spinnerMes.getValue();
            this.mesSelecionado = YearMonth.of(ano, mes);
            atualizarDashboard();
        }
    }//GEN-LAST:event_jMenuConfiguracoesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarTransação;
    private javax.swing.JLabel jLabelDashboard1;
    private javax.swing.JLabel jLabelDespesas;
    private javax.swing.JLabel jLabelMesSelecionado;
    private javax.swing.JLabel jLabelReceitas;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDespesas1;
    private javax.swing.JPanel jPanelReceitas1;
    private javax.swing.JPanel jPanelSaldo1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
