/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aurum.java;

import aurum.java.controller.TransactionController;
import java.awt.Color;
import java.text.NumberFormat;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Ethan
 */
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    private YearMonth mesSelecionado; // Variável para guardar o mês/ano

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        // Define o mês atual como padrão ao iniciar
        this.mesSelecionado = YearMonth.now();

        atualizarDashboard();
    }

    private void atualizarDashboard() {
        // Atualiza o JLabel com o mês selecionado
        Locale localeBrasil = new Locale("pt", "BR");
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("MMMM 'de' yyyy", localeBrasil);

        // Formata o texto e deixa a primeira letra maiúscula
        String mesFormatado = mesSelecionado.format(formatador);
        mesFormatado = mesFormatado.substring(0, 1).toUpperCase() + mesFormatado.substring(1);

        jLabelMesSelecionado.setText(mesFormatado);

        TransactionController transactionController = new TransactionController();
        double[] totais = transactionController.getDashboardTotals(this.mesSelecionado);

        double receitas = totais[0];
        double despesas = totais[1];
        double saldo = receitas - despesas;

        NumberFormat formatadorMoeda = NumberFormat.getCurrencyInstance(localeBrasil);
        jLabelReceitas.setText(formatadorMoeda.format(receitas));
        jLabelDespesas.setText(formatadorMoeda.format(despesas));
        jLabelSaldo.setText(formatadorMoeda.format(saldo));

        if (saldo < 0) {
            jLabelSaldo.setForeground(new Color(204, 0, 0));
        } else if (saldo > 0) {
            jLabelSaldo.setForeground(new Color(0, 204, 0));
        } else {
            jLabelSaldo.setForeground(Color.BLACK);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabelDashboard = new javax.swing.JLabel();
        jPanelReceitas = new javax.swing.JPanel();
        jLabelReceitas = new javax.swing.JLabel();
        jPanelDespesas = new javax.swing.JPanel();
        jLabelDespesas = new javax.swing.JLabel();
        jPanelSaldo = new javax.swing.JPanel();
        jLabelSaldo = new javax.swing.JLabel();
        jPanelBotoesAdicionarTransacao = new javax.swing.JPanel();
        jButtonAdicionarReceita = new javax.swing.JButton();
        jButtonAdicionarDespesa = new javax.swing.JButton();
        jLabelMesSelecionado = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuConfiguracoes = new javax.swing.JMenu();
        jMenuItemGerenciarCategorias = new javax.swing.JMenuItem();
        jMenuItemDefinirMes = new javax.swing.JMenuItem();
        jMenuTrasacoes = new javax.swing.JMenu();
        jMenuItemReceitas = new javax.swing.JMenuItem();
        jMenuItemDespesas = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aurum");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelDashboard.setText("Dashboard");

        jPanelReceitas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Receitas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 204, 51))); // NOI18N

        jLabelReceitas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelReceitas.setForeground(new java.awt.Color(0, 204, 0));
        jLabelReceitas.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelReceitasLayout = new javax.swing.GroupLayout(jPanelReceitas);
        jPanelReceitas.setLayout(jPanelReceitasLayout);
        jPanelReceitasLayout.setHorizontalGroup(
            jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelReceitasLayout.setVerticalGroup(
            jPanelReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReceitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelReceitas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelDespesas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Despesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(204, 0, 0))); // NOI18N

        jLabelDespesas.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelDespesas.setForeground(new java.awt.Color(204, 0, 0));
        jLabelDespesas.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelDespesasLayout = new javax.swing.GroupLayout(jPanelDespesas);
        jPanelDespesas.setLayout(jPanelDespesasLayout);
        jPanelDespesasLayout.setHorizontalGroup(
            jPanelDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDespesasLayout.setVerticalGroup(
            jPanelDespesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDespesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDespesas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSaldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabelSaldo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelSaldo.setText("R$ 0,00");

        javax.swing.GroupLayout jPanelSaldoLayout = new javax.swing.GroupLayout(jPanelSaldo);
        jPanelSaldo.setLayout(jPanelSaldoLayout);
        jPanelSaldoLayout.setHorizontalGroup(
            jPanelSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSaldoLayout.setVerticalGroup(
            jPanelSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaldoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSaldo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonAdicionarReceita.setText("+ Adicionar Receita");
        jButtonAdicionarReceita.setAlignmentY(0.0F);
        jButtonAdicionarReceita.setMaximumSize(new java.awt.Dimension(135, 24));

        jButtonAdicionarDespesa.setText("- Adicionar Despesa");
        jButtonAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesAdicionarTransacaoLayout = new javax.swing.GroupLayout(jPanelBotoesAdicionarTransacao);
        jPanelBotoesAdicionarTransacao.setLayout(jPanelBotoesAdicionarTransacaoLayout);
        jPanelBotoesAdicionarTransacaoLayout.setHorizontalGroup(
            jPanelBotoesAdicionarTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesAdicionarTransacaoLayout.createSequentialGroup()
                .addComponent(jButtonAdicionarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdicionarDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesAdicionarTransacaoLayout.setVerticalGroup(
            jPanelBotoesAdicionarTransacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonAdicionarReceita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonAdicionarDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabelMesSelecionado.setText("Mês");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelReceitas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDespesas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDashboard)
                        .addGap(18, 18, 18)
                        .addComponent(jPanelBotoesAdicionarTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelMesSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBotoesAdicionarTransacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jLabelMesSelecionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuConfiguracoes.setText("Configurações");

        jMenuItemGerenciarCategorias.setText("Gerenciar Categorias");
        jMenuItemGerenciarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGerenciarCategoriasActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemGerenciarCategorias);

        jMenuItemDefinirMes.setText("Definir Mês");
        jMenuItemDefinirMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDefinirMesActionPerformed(evt);
            }
        });
        jMenuConfiguracoes.add(jMenuItemDefinirMes);

        jMenuBar.add(jMenuConfiguracoes);

        jMenuTrasacoes.setText("Transações");

        jMenuItemReceitas.setText("Receitas");
        jMenuItemReceitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReceitasActionPerformed(evt);
            }
        });
        jMenuTrasacoes.add(jMenuItemReceitas);

        jMenuItemDespesas.setText("Despesas");
        jMenuTrasacoes.add(jMenuItemDespesas);

        jMenuBar.add(jMenuTrasacoes);

        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar.add(jMenuAjuda);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGerenciarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGerenciarCategoriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGerenciarCategoriasActionPerformed

    private void jMenuItemReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReceitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemReceitasActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jButtonAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDespesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionarDespesaActionPerformed

    private void jMenuItemDefinirMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDefinirMesActionPerformed
        // Spinner para o MÊS, com valor inicial do mês atual, mínimo 1, máximo 12
        JSpinner spinnerMes = new JSpinner(new SpinnerNumberModel(
                mesSelecionado.getMonthValue(), 1, 12, 1
        ));

        // Spinner para o ANO, com valor inicial do ano atual, minimo 1900, máximo 2500
        JSpinner spinnerAno = new JSpinner(new SpinnerNumberModel(
                mesSelecionado.getYear(), 1900, 2500, 1
        ));

        // Monta o painel que ficará dentro do diálogo
        JPanel painelSelecao = new JPanel();
        painelSelecao.add(new JLabel("Mês:"));
        painelSelecao.add(spinnerMes);
        painelSelecao.add(new JLabel("Ano:"));
        painelSelecao.add(spinnerAno);

        // Exibe o JOptionPane
        int resultado = JOptionPane.showConfirmDialog(
                this, // Janela pai (o próprio Dashboard)
                painelSelecao, // Componente customizado
                "Selecione o Mês e Ano", // Título da janela
                JOptionPane.OK_CANCEL_OPTION, // Botões OK e Cancelar
                JOptionPane.PLAIN_MESSAGE // Ícone
        );

        if (resultado == JOptionPane.OK_OPTION) {
            int ano = (int) spinnerAno.getValue();
            int mes = (int) spinnerMes.getValue();
            this.mesSelecionado = YearMonth.of(ano, mes);
            atualizarDashboard();
        }
    }//GEN-LAST:event_jMenuItemDefinirMesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarDespesa;
    private javax.swing.JButton jButtonAdicionarReceita;
    private javax.swing.JLabel jLabelDashboard;
    private javax.swing.JLabel jLabelDespesas;
    private javax.swing.JLabel jLabelMesSelecionado;
    private javax.swing.JLabel jLabelReceitas;
    private javax.swing.JLabel jLabelSaldo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuConfiguracoes;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemDefinirMes;
    private javax.swing.JMenuItem jMenuItemDespesas;
    private javax.swing.JMenuItem jMenuItemGerenciarCategorias;
    private javax.swing.JMenuItem jMenuItemReceitas;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenu jMenuTrasacoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBotoesAdicionarTransacao;
    private javax.swing.JPanel jPanelDespesas;
    private javax.swing.JPanel jPanelReceitas;
    private javax.swing.JPanel jPanelSaldo;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
