/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aurum.java;

import aurum.java.controller.TransactionController;
import aurum.java.model.Transaction;
import java.awt.HeadlessException;
import java.text.NumberFormat;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ethan
 */
public class PanelTransactions extends javax.swing.JPanel {

    private TransactionController controller;
    private Dashboard dashboard;

    /**
     * Creates new form PanelTransactions
     */
    public PanelTransactions(Dashboard dashboard) {
        initComponents();
        this.dashboard = dashboard;
        controller = new TransactionController();
        atualizarTabela();
    }

    public void atualizarTabela() {
        List<Transaction> lista = controller.listByMonth(dashboard.getMesSelecionado());
        DefaultTableModel model = (DefaultTableModel) jTableTransactions.getModel();
        model.setRowCount(0);

        Locale localeBrasil = new Locale("pt", "BR");
        NumberFormat formatadorMoeda = NumberFormat.getCurrencyInstance(localeBrasil);
        DateTimeFormatter formatadorData = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        for (Transaction t : lista) {
            String tipoFormatado = switch (t.getType()) {
                case "income" -> "Receita";
                case "expense" -> "Despesa";
                default -> t.getType();
            };

            String valorFormatado = formatadorMoeda.format(t.getAmount());
            String dataFormatada = t.getDate().format(formatadorData);
            String categoriaNome = (t.getCategory() != null) ? t.getCategory().getName() : "Sem categoria";

            model.addRow(new Object[]{
                t.getId(),
                t.getDescription(),
                valorFormatado,
                categoriaNome,
                dataFormatada,
                tipoFormatado
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTransactions = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCriar = new javax.swing.JButton();

        jTableTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Valor", "Categoria", "Data", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableTransactions);
        if (jTableTransactions.getColumnModel().getColumnCount() > 0) {
            jTableTransactions.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel1.setText("Digite o ID:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar))
                .addContainerGap())
        );

        jButtonCriar.setText("Criar Nova Transação");
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 242, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            String idText = jTextFieldID.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Por favor, digite o ID da transação que deseja excluir.",
                    "Campo Obrigatório",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int idParaExcluir = Integer.parseInt(idText);

            int resposta = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja EXCLUIR a transação de ID " + idParaExcluir + "?",
                "⚠️ Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (resposta == JOptionPane.YES_OPTION) {
                boolean excluida = controller.delete(idParaExcluir);

                if (excluida) {
                    JOptionPane.showMessageDialog(
                        this,
                        "Transação excluída com sucesso!",
                        "✓ Sucesso",
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    jTextFieldID.setText("");
                    atualizarTabela();
                    if (dashboard != null) {
                        dashboard.atualizarDashboard();
                    }
                } else {
                    JOptionPane.showMessageDialog(
                        this,
                        "Transação não encontrada com o ID: " + idParaExcluir + "\nVerifique se o ID está correto.",
                        "Transação Não Encontrada",
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "O ID deve ser um número inteiro válido.\nPor favor, verifique o valor digitado.",
                "Erro de Validação",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir transação.\nDetalhes: " + e.getMessage(),
                "Erro de Sistema",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            String idText = jTextFieldID.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this,
                    "Por favor, digite o ID da transação que deseja editar.",
                    "Campo Obrigatório",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int id = Integer.parseInt(idText);
            Transaction transacaoParaEditar = controller.getById(id);

            if (transacaoParaEditar == null) {
                JOptionPane.showMessageDialog(
                    this,
                    "Transação não encontrada com o ID: " + id + "\nVerifique se o ID está correto.",
                    "Transação Não Encontrada",
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            TransactionsFormView form = new TransactionsFormView(null, true, transacaoParaEditar);
            form.setLocationRelativeTo(this);
            form.setVisible(true);

            if (form.isSalvo()) {
                controller.update(form.getTransaction());
                atualizarTabela();
                if (dashboard != null) {
                    dashboard.atualizarDashboard();
                }
                JOptionPane.showMessageDialog(
                    this,
                    "Transação atualizada com sucesso!",
                    "✓ Sucesso",
                    JOptionPane.INFORMATION_MESSAGE
                );
                jTextFieldID.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this,
                "O ID deve ser um número inteiro válido.\nPor favor, verifique o valor digitado.",
                "Erro de Validação",
                JOptionPane.ERROR_MESSAGE
            );
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                this,
                "Ocorreu um erro ao editar a transação.\nDetalhes: " + e.getMessage(),
                "Erro de Sistema",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        TransactionsFormView form = new TransactionsFormView(null, true, "income");
        form.setLocationRelativeTo(this);
        form.setVisible(true);

        if (form.isSalvo()) {
            controller.save(form.getTransaction());
            atualizarTabela();
            if (dashboard != null) {
                dashboard.atualizarDashboard();
            }
            JOptionPane.showMessageDialog(
                this,
                "Transação criada com sucesso!",
                "✓ Sucesso",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTransactions;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
