/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aurum.java;

import aurum.java.controller.CategoryController;
import aurum.java.model.Category;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ethan
 */
public class PanelCategorias extends javax.swing.JPanel {

    private CategoryController controller;

    /**
     * Creates new form PanelCategorias
     */
    public PanelCategorias() {
        initComponents();
        controller = new CategoryController();
        atualizarTabela();
    }

    private void atualizarTabela() {
        List<Category> lista = controller.listAll();
        DefaultTableModel model = (DefaultTableModel) jTableCategories.getModel();
        model.setRowCount(0);

        for (Category c : lista) {
            String tipoFormatado = "";
            tipoFormatado = switch (c.getType()) {
                case "income" ->
                    "Receita";
                case "expense" ->
                    "Despesa";
                default ->
                    c.getType();
            };

            model.addRow(new Object[]{
                c.getId(),
                c.getName(),
                tipoFormatado
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCategories = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonCriar = new javax.swing.JButton();

        jTableCategories.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableCategories);
        if (jTableCategories.getColumnModel().getColumnCount() > 0) {
            jTableCategories.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        jLabel1.setText("Digite o ID:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar))
                .addContainerGap())
        );

        jButtonCriar.setText("Criar Nova Categoria");
        jButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCriar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            String idText = jTextFieldID.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Por favor, digite o ID da categoria que deseja excluir.", 
                    "Campo Obrigatório", 
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int idParaExcluir = Integer.parseInt(idText);

            int resposta = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja EXCLUIR a categoria de ID " + idParaExcluir + "?\nIsso afetará todas as transações ligadas a ela (vão ficar sem categoria).",
                    "⚠️ Confirmar Exclusão",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (resposta == JOptionPane.YES_OPTION) {
                boolean excluida = controller.delete(idParaExcluir);

                if (excluida) {
                    JOptionPane.showMessageDialog(
                        this, 
                        "Categoria excluída com sucesso!", 
                        "✓ Sucesso", 
                        JOptionPane.INFORMATION_MESSAGE
                    );
                    jTextFieldID.setText("");
                    atualizarTabela();
                } else {
                    JOptionPane.showMessageDialog(
                        this, 
                        "Categoria não encontrada com o ID: " + idParaExcluir + "\nVerifique se o ID está correto.", 
                        "Categoria Não Encontrada", 
                        JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this, 
                "O ID deve ser um número inteiro válido.\nPor favor, verifique o valor digitado.", 
                "Erro de Validação", 
                JOptionPane.ERROR_MESSAGE
            );
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                this, 
                "Erro ao excluir categoria.\nDetalhes: " + e.getMessage(), 
                "Erro de Sistema", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        try {
            String idText = jTextFieldID.getText().trim();
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Por favor, digite o ID da categoria que deseja editar.", 
                    "Campo Obrigatório", 
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int id = Integer.parseInt(idText);
            Category categoriaParaEditar = controller.getById(id);

            if (categoriaParaEditar == null) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Categoria não encontrada com o ID: " + id + "\nVerifique se o ID está correto.", 
                    "Categoria Não Encontrada", 
                    JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            CategoriesFormView form = new CategoriesFormView(null, true, categoriaParaEditar);
            form.setVisible(true);

            if (form.isSalvo()) {
                controller.update(form.getCategory());
                atualizarTabela();
                JOptionPane.showMessageDialog(
                    this, 
                    "Categoria atualizada com sucesso!", 
                    "✓ Sucesso", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                jTextFieldID.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                this, 
                "O ID deve ser um número inteiro válido.\nPor favor, verifique o valor digitado.", 
                "Erro de Validação", 
                JOptionPane.ERROR_MESSAGE
            );
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(
                this, 
                "Ocorreu um erro ao editar a categoria.\nDetalhes: " + e.getMessage(), 
                "Erro de Sistema", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarActionPerformed
        CategoriesFormView form = new CategoriesFormView(null, true);
        form.setLocationRelativeTo(this);
        form.setVisible(true);

        if (form.isSalvo()) {
            controller.save(form.getCategory());
            atualizarTabela();
            JOptionPane.showMessageDialog(
                this, 
                "Categoria criada com sucesso!", 
                "✓ Sucesso", 
                JOptionPane.INFORMATION_MESSAGE
            );
        }
    }//GEN-LAST:event_jButtonCriarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCategories;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
